### ISSUE TITLE
Segmentation fault :11 on mac os high sierra (10.13.4)

### ISSUE THREAD

**Issue by romit7** [briangann/predix-chisel-postgres#11]
If I manually run the command from the bin folder I am getting the following error when I am trying to connect to postgres db
```
bin git:(master) ./chisel_darwin_amd64 client -v --keepalive 3s https://smart-shop-support-chisel-postgres.run.aws-usw02-pr.ice.predix.io 15524:db-25a2f3f6-0111-4720-927c-939f95ef3ba5.c7uxaqxgfov3.us-west-2.rds.amazonaws.com:5432
[1]    67426 segmentation fault  ./chisel_darwin_amd64 client -v --keepalive 3s  

```
This was running fine on mac os sierra or lower versions

**Comment by briangann** [comment]
you can get a current build of chisel from here: https://github.com/jpillora/chisel/releases

**Comment by romit7** [comment]
Thanx Brian, taking the latest binaries it is working now

**Comment by xiaoyan-huang-bhc3** [comment]
Hi Brian,
I have the same error message and solved it by downloading the latest build of chisel.  However,  in my terminal,  it keep printing "<WARNING> non-binary msg".  Any hint about solving this issue?  Thanks!


<img width="853" alt="screen shot 2018-08-20 at 3 10 54 pm" src="https://user-images.githubusercontent.com/22775564/44367026-bc380f00-a48b-11e8-9d27-51f55da26dc0.png">
