### ISSUE TITLE
Getting segmentation fault: 11 while launching predix chisel from Mac os High Siera

### ISSUE THREAD

**Issue by anupamdas24** [briangann/predix-chisel-postgres#8]
After the security update on my mac, while I am attempting to launch the predix chisel from the terminal, it is showing below issue.
Segmentation fault: 11

**Comment by briangann** [comment]
You'll need to use the binaries available at https://github.com/jpillora/chisel/releases

I ran them on my mac high sierra laptop and they work correctly.

I'll update to 10.13.3 and verify (I only tried with update 10.13.2)

**Comment by anupamdas24** [comment]
Thanks , it worked. Perfect thnks
